### ISSUE TITLE
 New METS profile: Electronic Archive of Galician Heritage METS Profile

### ISSUE THREAD

**Issue by thabing** [mets/METS-board#22]
[Galiciana_Digital_Archive_of_Galicia.docx](https://github.com/mets/METS-board/files/1085243/Galiciana_Digital_Archive_of_Galicia.docx)

We have developed an Archives Digital Project, Galiciana: Digital Archive of Galicia, in which 34 Archives from Galicia participate, and we have also defined our own METS profile for Archival Digital Objetcs. We are interested in adding our Project to the METS Implementation Registry and registering our METS profile with the Library of Congress Network Development and MARC Standards Office, as well.

**Comment by thabing** [comment]
Sent acknowledgement to sender and sent request for volunteer to METS Board.

**Comment by thabing** [comment]
Dear METS Editorial Board Members,

I am looking for a volunteer to steer this request forward.  I’ve replied to the submitter that someone from the METS Board will be contacting them soon.  I’ve also added an issue to GitHub,  https://github.com/mets/METS-board/issues/22, and also a Trello card to discuss this at the next meeting.

I think this person is asking for two things, an entry in the implementation registry, http://www.loc.gov/standards/mets/mets-registry.html, and also a profile.  Their attached document is probably adequate for the registry, so if after a quick review it looks OK, we can ask Glenn at LoC to add the entry.  Also if someone could contact them and explain the process for creating and registering a profile, that would be great.

We can discuss at the next meeting.

Kind regards,

Tom Habing

**Comment by tingletech** [comment]
I don't have a real easy way to open .docx; so I uploaded it to google docs

https://docs.google.com/document/d/1KxQHh8hemYMkasj3bU3X4ZTKHYiGCTQJOuP0CApKzTw/edit?usp=sharing

**Comment by thabing** [comment]
Asked Glenn to add Implementation Registry entry.

**Comment by thabing** [comment]
Initiated public review of the profile:  https://github.com/mets/METS-profiles/blob/master/00000046.xml

**Comment by thabing** [comment]
Registry entry completed by Glenn:  http://www.loc.gov/standards/mets/mets-registry.html#galiciana

**Comment by thabing** [comment]
Profile has been registered:  http://www.loc.gov/standards/mets/profiles/00000046.xml
