### ISSUE TITLE
Rosetta Mets - DMDSEC

### ISSUE THREAD

**Issue by Rajasekaranal** [mets/METS-board#23]
As reviewed the Rosetta Mets structure (below link), found that no option available for creating article metadata.
http://www.loc.gov/standards/mets/profiles/00000042.xml
It was mentioned as "**Only one level for IE level"** & "**One level for file (page) level**", if more than one articles present in the single page, then how can we structure. Kindly let us know any possibilities.

Thanks,
Rajasekaran A.

**Comment by thabing** [comment]
Hi Rajasekaran,

This profile supports the ExLibris Rosetta Digital Asset Management system.  It is being hosted by the METS Board as a courtesy to the company.

Your best source of information would be ExLibris’ technical support channels.  Their support contact is: rosetta.support@exlibrisgroup.com<mailto:rosetta.support@exlibrisgroup.com>.

There is also a mailing list that may be a good venue for technical questions about the profile:  http://el-una.org/mailing-lists/rosetta-mailing-lists/

You might also try the generic METS mailing list, https://listserv.loc.gov/cgi-bin/wa?A0=METS, which is mostly about METS in general, but probably has some other users of the Rosetta product.

Kind regards,

Tom Habing

**Comment by thabing** [comment]
There has been no further correspondence since the above reply was sent.  Closing this ticket
