### ISSUE TITLE
Possibly add xsd:anyattribute to the agent/note element

### ISSUE THREAD

**Issue by thabing** [mets/METS-board#24]
"working with our non-registered profile of METS I have encountered a need of being able to type the note in agent so it would be possible to say what kind of information the note have. Have gotten the same comment from some other collegues also working with it. So perhaps the xsd:anyattribute could be made possible here too so the schema dont have to handle the typing of the note with attributes type and othertype (setting up the valuelist for type, well not to easy)?"

From Karin's note to METS-Board of Sept. 6.

**Comment by thabing** [comment]
Changes made (May 2018) and posted for public comment (June 2018)

**Comment by karinbredenberg** [comment]
When requesting updating at loc.gov, add an updated version of the help document created from the schema. The one posted there is version 1.9.

**Comment by thabing** [comment]
The new 1.12 schema is now published here:  http://www.loc.gov/standards/mets/mets.xsd and http://www.loc.gov/standards/mets/version112/mets.xsd.

I'm going to close this ticket and open a new one to update the documentation from 1.9 to 1.12
