### ISSUE TITLE
Provide clarification of the METSRights schema

### ISSUE THREAD

**Issue by thabing** [mets/METS-board#25]
"the METSRight schema I've have gotten questions regarding changes it from the Archives Portal Europe Foundation. Or more they planned to change the schema and use values from the Europeana rights statments instead of the ones present in the schema as typing of the rights and I said well it wont be the METSRights schema if you do that, it wont validate with the original schema and all those ususal comments of using a standard. They have for now decided to use the othertyping-attribute but there will come more from them as I understood the conversation and they want to change the METSRights schema. We need to put something up regarding it, who owns it, if we recommend the use and so on. And not to forget it is used in registered profiles so something needs to be done I guess."

From Karin's note to METS-Board of Sept. 6

**Comment by aelkiss** [comment]
At this point we have an updated version that we can post here on GitHub.

**Comment by aelkiss** [comment]
It has been posted on the LC site.
