### ISSUE TITLE
Outdated Documentation Here: http://www.loc.gov/standards/mets/mets-schemadocs.html

### ISSUE THREAD

**Issue by thabing** [mets/METS-board#28]
The documents, http://www.loc.gov/standards/mets/mets-schemadocs.html, need to be updated to reflect the current version of the schema:

    METS Schema 1.9 Documentation
    METS Schema 1.9 METS Structure Diagram
    METS Version 1 namespace page: information about the version 1 target namespace URI

**Comment by aelkiss** [comment]
It looks like the link to the structure diagram (http://sunsite.berkeley.edu/mets/diagram) is currently returning a 403 Forbidden error.

The documentation was automatically generated with https://www.loc.gov/standards/mets/profile_docs/xsd2doc.xsl, but there might be something better out there to use to regenerate the item. @thabing  will look into it.

**Comment by aelkiss** [comment]
We will try changing the revision history comments to xsd documentation elements, then re-generating the docs with this tool. @karinbredenberg  will check with Glenn to see if it is feasible to host the entire generated folder on the LoC web site.

**Comment by aelkiss** [comment]
I re-generated the docs with the version history in annotations and split up by element and with SVG images instead of JPEG. https://mets.github.io/METS_Docs_history_svg/mets.html

This is for draft version 1.13, see https://github.com/mets/METS-schema/pull/1

**Comment by aelkiss** [comment]
Draft version 1.13 = published version 1.12.1 (we did not actually need a minor version bump as there were no functional changes). This is now up at https://mets.github.io/METS_Docs/mets.html. I verified it is linked from http://www.loc.gov/standards/mets/mets-schemadocs.html. I will close this issue.
