### ISSUE TITLE
Incorrect link in METS Profiles

### ISSUE THREAD

**Issue by kieranjol** [mets/METS-board#48]
https://www.loc.gov/standards/mets/mets-examples.html
I notice that when I click the bottom 'Home' link, it send you to https://www.loc.gov/folklife/ rather than https://www.loc.gov/standards/mets/mets-home.html - which is the target of the Home link at the top of the page.

Best,

Kieran O'Leary
National Library of Ireland

**Comment by karinbredenberg** [comment]
Work with updating the METS webpage at loc.gov is on-going.

**Comment by ntra00** [comment]
This has been fixed!

**Comment by kieranjol** [comment]
Thank you!
